#Домашнє завдання до тем apply(), groupby(), pivot_table()

В цьому домашньому завданні продовжуємо працювати з набором даних `supermarket_sales.csv`.

0. Імпортуйте бібліотеку pandas та зчитайте дані у змінну `df` типу `pandas.DataFrame`.

In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
df = pd.read_csv('drive/MyDrive/Colab/supermarket_sales.csv')

In [4]:
df.head(5)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3

1. Дослідимо, який філіал супермаркету ('Branch') є найприбутковішим. Для цього знайдіть сумарний прибуток за кожним філіалом і виявіть, який філіал має найвищий.

In [5]:
df.groupby('Branch')['Total'].sum()

Branch
A    106200.3705
B    106197.6720
C    110568.7065
Name: Total, dtype: float64

2. В якому місті знайходиться філіал з найвищим прибутком? Може в тому місці нам розмітисти ще один магазин.  
Знайдіть відповідь за допомогою функціоналу Pandas.

In [6]:
df.groupby(by=['Branch', 'City'])['Total'].sum()

Branch  City
A       Yangon       106200.3705
B       Mandalay     106197.6720
C       Naypyitaw    110568.7065
Name: Total, dtype: float64

3.1. Створіть зводну таблицю, яка покаже, скільки покупок (інвойсів) було зроблено в кожній з філій (`Branch`) за різними категоріями товарів. Запишіть таблицю в змінну `invoices_by_category` і виведіть змінну на екран.
Ця таблиця допоможе проаналізувати, в якій філії купують найбільше товарів кожної з категорій.

In [7]:
invoices_by_category = df.pivot_table(index='Branch', columns='Product line', values='Invoice ID', aggfunc='count')

In [8]:
invoices_by_category

Product line,Electronic accessories,Fashion accessories,Food and beverages,Health and beauty,Home and lifestyle,Sports and travel
Branch,,,,,,
A,60,51,58,47,65,59
B,55,62,50,53,50,62
C,55,65,66,52,45,45

Очікуваний результат:

![](https://drive.google.com/uc?export=view&id=1rueAdko6S3UxIHGtojetTxlES-EyM6Yb)

3.2. Викристовуючи змінну `invoices_by_category` дайте відповідь програмно (тобто значення треба не просто знайти очима, а вивести за допомогою коду), в якому філіалі магазину (`Branch`) найбільше інвойсів із покупкою товарів категорії "Електронні аксесуари" (`Electronic accessories`)?

In [9]:
pd.pivot_table(df, values=['Invoice ID'], index=['Branch'], columns=['Product line'],
               aggfunc= 'count')
max_branch = invoices_by_category['Electronic accessories'].idxmax()
max_count = invoices_by_category['Electronic accessories'].max()

print(f"Найбільше інвойсів в філіалі {max_branch} і дорівнює {max_count}")

Найбільше інвойсів в філіалі A і дорівнює 60

4-6. **Творче завдання на розвиток аналітичного мислення**

Крок 1. Сформулюйте ТРИ питання (гіпотези) до наявних даних, які допомогли б вам зрозуміти, які користувачі що, де та коли найбільше/найменше купують, аби дати на основі цих гіпотез рекомендації бізнесу. Звісно питання мають бути не тими, на які ми вже відповіли в завданнях модулю.

Крок 2. Знайдіть відповіді на свої питання з допомогою функціоналу pandas.

Крок 3. Напишіть, як відповідь на це питання може бути використана для прийняття бізнес рішень.   
   
 Питання можуть бути будь-якої складності, але їх має бути 3. Кожне питання оцінюється як 1 завдання. Без виконання цього завдання ДЗ не приймається. Якщо є питання щодо виконання - пишіть у чат 🙌

1.

 Для магазинів в філіалі А найменш актуальні товари в категорії Модні Аксесуари та Здоров'я та краса. Це може бути пов'язане з тим що в місті проживає категорія людей 50+, які більш охоче витрачають кошти на подорожі, гаджети, їжу і будинок. Тому питання номер 1, визначити вікову категорію людей для гілок філіалів А, В, С. Але в таблиці немає данних про вік, тому можна зробити висновок стосовно гендеру для кожного філіалу.
Для філіала А може переважати кількість чоловіків, оскільки вони не надто турбуються за своє здоров'я (не відвідують лікарів так часто як жінки в цілях профілактики) і також не витрачаються особливо на модні аксесуари.

Питання №1: Визначити кількість осіб чоловічої та жіночої статі і кількість здійснених покупок для гілок А, В, С.

In [17]:
df['Gender'].value_counts()

Gender
Female    501
Male      499
Name: count, dtype: int64

In [11]:
invoices_by_gender = df.pivot_table(index='Branch', columns='Gender', values='Invoice ID', aggfunc='count')
invoices_by_gender

Gender  Female  Male
Branch
A          161   179
B          162   170
C          178   150

In [24]:
df.groupby(by=['Branch', 'Gender'])['Invoice ID'].count()

Branch  Gender
A       Female    161
        Male      179
B       Female    162
        Male      170
C       Female    178
        Male      150
Name: Invoice ID, dtype: int64

Для філіалів А і В потрібно розширити категорії товарів для чоловіків, оскільки в цих магазинах кількість покупок серед чоловіків домінує, тому логічно що більгий асортимент може спровокувати чоловіків на більшу кількість покупок.
Для філіалу С навпаки потрібно розширити асортимент товарів для жінок, оскільки це може збільшити загальну кількість покупок однією людиною.

2.

Маючи дані про середній чек покупки, можна проанаізувати хто з жінок / чоловіків має більшу купівельну спроможність в різних філіалах. Це може вказати на те, які товари будуть більш пріоритетні в даному магазині. (для чоловіків це техніка, для жінок - товари для здоров', краси, побуту - і в залежності від цих данних акцентувати асортимент).

Питання №2: Визначити який середній чек покупки для кожного філіалу в залежності від гендеру.

In [18]:
mean_unit_price = df.pivot_table(index='Branch', columns='Gender', values='Unit price', aggfunc='mean')
mean_unit_price

Gender     Female       Male
Branch
A       56.086149  53.606816
B       54.168148  57.080235
C       55.517584  57.904200

In [23]:
df.groupby(by=['Branch', 'Gender'])['Unit price'].mean()

Branch  Gender
A       Female    56.086149
        Male      53.606816
B       Female    54.168148
        Male      57.080235
C       Female    55.517584
        Male      57.904200
Name: Unit price, dtype: float64

На основі цих даних можна помітити те що в філіалі А середній чек покупки в жінок домінує хоч і кількість покупок здійснило більше чоловіків. Отже жінки купували більш дороговартісні товари. Можна розширити лінійку жіночого одягу і аксесуарів більш преміальними брендами.
А в філіалі С, навпаки, чоловіки витратили більше, хоча більша кількість покупок була здійснена жінками. Тому в цьому випадку треба так само розшири асортимент для чоловіків більш перміальними позиціями.

3.

Також дослідимо який метод оплати найактуальніший і найзручніший в усій статистиці.

Питання №3: Визначити кількість оплат різними методами і з'ясувати який метод найпопулярніший.

In [21]:
df['Payment'].value_counts()

Payment
Ewallet        345
Cash           344
Credit card    311
Name: count, dtype: int64

Електронний гаманець так само зручно використовувати як і готівку, можливо потрібно якось полегшити моменти оплати готівкою, оскільки покупцям це зручно.
Наприклад автоматизовані каси які приймають купюри, не задіювати при цьому касирів.